### ISSUE TITLE
I finally implemented a plugin for Telegram

### ISSUE THREAD

**Issue by nudred** [cosmocode/dokuwiki-plugin-twofactor#5]
Yes, I don't like PHP very much. But since the Core Plugin was rewritten, and I wrote the Telegram plugin last time, I had to do it 😄

I took Alternate Email plugin as a basic and changed it a little

I installed the plugin and checked. Works as it should
The only thing. I tested the plugin on the **"Hogfather"** version

I would be grateful if someone would check the plugin in the **"Igor"** version
And marked as **"Compatible"**

[GitHub Source](https://github.com/nudred/twofactortelegram)
[DokuWiki Plugin Page](https://www.dokuwiki.org/plugin:twofactortelegram)

**Comment by splitbrain** [comment]
Awesome!
