### ISSUE TITLE
Way to pull 2FA auth result as event?

### ISSUE THREAD

**Issue by alexdraconian** [cosmocode/dokuwiki-plugin-twofactor#9]
Are there any plans to add own event or something? I couldn't find way to know if user passes/fails 2FA by another plugin.

**Comment by splitbrain** [comment]
Can you describe your actual use case please?

**Comment by alexdraconian** [comment]
Recent update removed loglog plugin support, so I want to make another plugin to log 2FA pass/fail.

**Comment by splitbrain** [comment]
I think it would be more sensible to send a PR adding loglog support back in.
